[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "protein_binding_affinity"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=8.4.1,<9"
black = ">=25.1.0,<26"
pre-commit = ">=4.2.0,<5"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.1,<2"
requests = ">=2.32.4,<3"
biopython = ">=1.85,<2"
ipykernel = ">=6.30.1,<7"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.5,<8"


[pypi-dependencies]
protein_binding_affinity = { path = ".", editable = true }
