[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["pytorch", "conda-forge"]
description = "Add a short description here"
name = "protein_binding_affinity"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=8.4.1,<9"
black = ">=25.1.0,<26"
pre-commit = ">=4.2.0,<5"
pytorch = ">=2.5.1,<3"
pandas = ">=2.3.1,<3"
matplotlib = ">=3.9.1,<4"
seaborn = ">=0.13.2,<0.14"
requests = ">=2.32.4,<3"
biopython = ">=1.85,<2"
ipykernel = ">=6.30.1,<7"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.5,<8"
transformers = ">=4.17.0,<5"
rdkit = ">=2023.3.3,<2024"
numpy = "1.26.4"
scipy = "1.11.4"
scikit-learn = "1.3.2"

[pypi-dependencies]
protein_binding_affinity = { path = ".", editable = true }
